import dotenv from "dotenv";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import WasteGuide from "../models/recycling/WasteGuide.js";
import RecyclingCenter from "../models/recycling/RecyclingCenter.js";
import EducationArticle from "../models/recycling/EducationArticle.js";

dotenv.config();

const WEEKDAY = { open: "08:00", close: "17:00", closed: false };
const SATURDAY = { open: "08:00", close: "13:00", closed: false };
const CLOSED = { open: "", close: "", closed: true };

const defaultHours = {
  monday: WEEKDAY,
  tuesday: WEEKDAY,
  wednesday: WEEKDAY,
  thursday: WEEKDAY,
  friday: WEEKDAY,
  saturday: SATURDAY,
  sunday: CLOSED,
};

const GUIDES = [
  {
    name: "Plastic Bottle",
    slug: "plastic-bottle",
    category: "Plastic",
    description:
      "Common PET plastic bottles used for beverages. Widely accepted at recycling centres when clean and empty.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Recyclable",
    preparationInstructions: [
      "Empty the bottle completely",
      "Rinse if necessary to remove residue",
      "Separate the cap if your centre requires it",
      "Flatten to save space when possible",
    ],
    dos: [
      "Keep plastic bottles separate from other waste",
      "Place clean plastic in the appropriate recycling stream",
      "Check local centre rules for caps and labels",
    ],
    donts: [
      "Do not burn plastic",
      "Do not mix heavily contaminated bottles with recyclables",
      "Do not put soft film or polythene with rigid PET bottles",
    ],
    acceptedItems: ["PET bottles", "Water bottles", "Soft drink bottles"],
    rejectedItems: ["Heavily contaminated plastic", "Multilayer packaging", "Soft plastic film"],
    disposalMethods: ["Recycling center", "Municipal collection"],
    environmentalImpact:
      "Recycling PET reduces demand for virgin plastic and keeps bottles out of drains and waterways.",
    keywords: ["plastic", "bottle", "pet", "water bottle", "soft drink", "beverage"],
    faqs: [
      {
        question: "Should plastic bottles be washed?",
        answer:
          "A quick rinse is enough. Follow the instructions of your local recycling service.",
      },
      {
        question: "Can I recycle bottle caps?",
        answer:
          "Some centres accept caps; others ask you to remove them. Check the centre details.",
      },
    ],
    language: "en",
    status: "published",
  },
  {
    name: "Battery",
    slug: "battery",
    category: "Batteries",
    description:
      "Household, rechargeable, and car batteries contain materials that must not go in ordinary garbage.",
    image: "https://images.unsplash.com/photo-1609091839319-d5361ba8f32e?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Keep batteries separate from other waste",
      "Do not crush or burn batteries",
      "Store damaged batteries in a non-conductive container",
      "Take them to an approved collection or e-waste point",
    ],
    dos: [
      "Use approved battery collection centres",
      "Keep batteries dry and cool until disposal",
      "Follow centre instructions for damaged cells",
    ],
    donts: [
      "Don't throw batteries into normal garbage",
      "Don't burn batteries",
      "Don't damage or short-circuit batteries",
    ],
    acceptedItems: [
      "Household AA/AAA batteries",
      "Rechargeable batteries",
      "Car batteries (at specialised points)",
    ],
    rejectedItems: ["Batteries mixed into household bins"],
    disposalMethods: ["E-waste center", "Hazardous waste facility", "Special collection event"],
    environmentalImpact:
      "Batteries can leach heavy metals into soil and water if dumped in landfill.",
    keywords: [
      "battery",
      "batteries",
      "car battery",
      "rechargeable",
      "aa",
      "aaa",
      "lithium",
      "hazardous",
    ],
    faqs: [
      {
        question: "Can I put batteries in normal garbage?",
        answer:
          "No. Use an appropriate battery collection or recycling point.",
      },
    ],
    language: "en",
    status: "published",
  },
  {
    name: "Laptop",
    slug: "laptop",
    category: "E-Waste",
    description:
      "End-of-life laptops and notebooks are e-waste and must go to certified electronics recyclers.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Back up and wipe personal data if possible",
      "Remove removable batteries if the centre asks",
      "Keep chargers and cables with the device when accepted",
      "Take to a certified e-waste centre",
    ],
    dos: [
      "Use certified e-waste centres only",
      "Ask about data destruction options",
      "Donate working devices when possible",
    ],
    donts: [
      "Do not place laptops in household garbage",
      "Do not burn or dismantle with household tools",
      "Do not dump near waterways",
    ],
    acceptedItems: ["Laptops", "Notebooks", "Chargers (check centre)"],
    rejectedItems: ["Devices mixed into general waste"],
    disposalMethods: ["E-waste center", "Reuse", "Donation center"],
    environmentalImpact:
      "E-waste contains valuable metals and hazardous materials that need specialised processing.",
    keywords: ["laptop", "notebook", "computer", "e-waste", "electronics", "old laptop"],
    faqs: [
      {
        question: "Can I put an old laptop in the bin?",
        answer: "No. Use a certified e-waste centre or a recycler pickup.",
      },
    ],
    language: "en",
    status: "published",
  },
  {
    name: "Mobile Phone",
    slug: "mobile-phone",
    category: "E-Waste",
    description: "Old phones and smartphones should be recycled or donated—not binned.",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Factory-reset or wipe the device",
      "Remove SIM and memory cards",
      "Take to an e-waste or collection point",
    ],
    dos: ["Donate working phones", "Use certified e-waste centres"],
    donts: ["Do not throw phones in household garbage"],
    acceptedItems: ["Smartphones", "Feature phones", "Phone batteries (separate if required)"],
    rejectedItems: ["Phones in mixed household waste"],
    disposalMethods: ["E-waste center", "Donation center", "Reuse"],
    environmentalImpact: "Phones contain recoverable metals and hazardous components.",
    keywords: ["mobile", "phone", "smartphone", "old phone", "cellphone", "e-waste", "elec"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Glass Bottle",
    slug: "glass-bottle",
    category: "Glass",
    description: "Glass bottles and jars can usually be recycled when rinsed and unbroken.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Recyclable",
    preparationInstructions: [
      "Rinse bottles and jars",
      "Remove lids if required by the centre",
      "Sort by colour if asked",
    ],
    dos: ["Keep glass separate", "Handle broken glass safely"],
    donts: ["Do not include mirrors, bulbs, or ceramics with bottle glass"],
    acceptedItems: ["Glass bottles", "Glass jars"],
    rejectedItems: ["Mirrors", "Light bulbs", "Window glass", "Ceramics"],
    disposalMethods: ["Recycling center", "Municipal collection"],
    environmentalImpact: "Glass can be recycled repeatedly without loss of quality.",
    keywords: ["glass", "bottle", "jar", "glass bottle"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Cardboard",
    slug: "cardboard",
    category: "Cardboard",
    description: "Clean, dry cardboard boxes and cartons are widely recyclable.",
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Recyclable",
    preparationInstructions: [
      "Flatten boxes",
      "Remove plastic tape and foam inserts when possible",
      "Keep cardboard dry",
    ],
    dos: ["Stack flattened cardboard", "Recycle clean cartons"],
    donts: ["Do not recycle greasy or heavily soiled cardboard"],
    acceptedItems: ["Corrugated boxes", "Shipping cartons", "Clean cardboard"],
    rejectedItems: ["Greasy pizza boxes", "Wet or mouldy cardboard"],
    disposalMethods: ["Recycling center", "Municipal collection"],
    environmentalImpact: "Recycling cardboard saves trees and landfill space.",
    keywords: ["cardboard", "box", "carton", "packing", "paper"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Paper",
    slug: "paper",
    category: "Paper",
    description: "Newspapers, magazines, and office paper belong in the paper recycling stream when dry.",
    image: "https://images.unsplash.com/photo-1456513080800-b6bbe16bb23e?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Recyclable",
    preparationInstructions: ["Keep paper dry", "Remove plastic wraps", "Bundle if required"],
    dos: ["Separate paper from food waste", "Recycle clean paper"],
    donts: ["Do not recycle tissue, napkins, or heavily soiled paper"],
    acceptedItems: ["Newspaper", "Magazines", "Office paper"],
    rejectedItems: ["Tissue", "Greasy paper", "Carbon paper"],
    disposalMethods: ["Recycling center", "Municipal collection"],
    environmentalImpact: "Paper recycling reduces deforestation pressure.",
    keywords: ["paper", "newspaper", "magazine", "office paper"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Metal Can",
    slug: "metal-can",
    category: "Metal",
    description: "Aluminium and steel food cans are recyclable after a quick rinse.",
    image: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Recyclable",
    preparationInstructions: ["Empty and rinse cans", "Crush if space is limited"],
    dos: ["Keep metal separate", "Take larger scrap to a scrap collector"],
    donts: ["Do not mix with hazardous containers"],
    acceptedItems: ["Aluminium cans", "Steel cans", "Tin cans"],
    rejectedItems: ["Pressurised aerosol cans (unless centre accepts)", "Paint cans with residue"],
    disposalMethods: ["Recycling center", "Scrap collector", "Municipal collection"],
    environmentalImpact: "Recycling metal saves significant energy versus mining ore.",
    keywords: ["metal", "can", "aluminium", "steel", "tin", "scrap"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Food & Garden Waste",
    slug: "organic-waste",
    category: "Organic Waste",
    description: "Kitchen scraps and garden waste can be composted at home or at a compost facility.",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Compostable",
    preparationInstructions: [
      "Separate food scraps from packaging",
      "Use a compost bin or municipal organic collection",
      "Avoid meat/dairy in home compost if it attracts pests",
    ],
    dos: ["Compost at home when possible", "Use municipal organic collection days"],
    donts: ["Do not mix plastics with organic waste"],
    acceptedItems: ["Food scraps", "Garden waste", "Leaves"],
    rejectedItems: ["Plastic bags", "Synthetic packaging"],
    disposalMethods: ["Compost facility", "Municipal collection", "Reuse"],
    environmentalImpact: "Composting returns nutrients to soil and cuts methane from landfill.",
    keywords: ["organic", "food", "garden", "compost", "kitchen", "leaves"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Clothing & Textiles",
    slug: "textiles",
    category: "Textiles",
    description: "Wearable clothes can be donated; damaged textiles may go to textile recycling.",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Reusable",
    preparationInstructions: [
      "Clean and dry garments before donation",
      "Separate reusable items from rags",
      "Take to a donation or textile recycling point",
    ],
    dos: ["Donate wearable clothes", "Reuse bags and fabric when possible"],
    donts: ["Do not dump wet or mouldy textiles at donation centres"],
    acceptedItems: ["Wearable clothing", "Clean textiles", "Shoes (pair)"],
    rejectedItems: ["Heavily soiled or hazardous contaminated textiles"],
    disposalMethods: ["Donation center", "Reuse", "Recycling center"],
    environmentalImpact: "Extending garment life reduces textile waste and water use.",
    keywords: ["textile", "clothing", "clothes", "fabric", "donation", "shirt"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Bulky Furniture",
    slug: "bulky-waste",
    category: "Bulky Waste",
    description:
      "Large items like sofas and mattresses need special collection or donation—not regular bins.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    recyclable: false,
    recyclabilityType: "Conditionally Recyclable",
    preparationInstructions: [
      "Contact your municipality for bulky collection",
      "Donate usable furniture",
      "Disassemble if required for transport",
    ],
    dos: ["Arrange special collection", "Donate usable items"],
    donts: ["Do not dump bulky waste on roadsides"],
    acceptedItems: ["Sofas", "Mattresses", "Large furniture (centre-dependent)"],
    rejectedItems: ["Items left as illegal dumping"],
    disposalMethods: ["Special collection event", "Donation center", "Municipal collection"],
    environmentalImpact: "Illegal dumping of bulky waste harms public spaces and drainage.",
    keywords: ["bulky", "furniture", "sofa", "mattress", "couch"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Rechargeable Battery",
    slug: "rechargeable-battery",
    category: "Batteries",
    description: "Lithium and NiMH rechargeable batteries need specialised recycling.",
    image: "https://images.unsplash.com/photo-1609091839319-d5361ba8f32e?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Tape terminals if advised",
      "Keep cool and dry",
      "Take to an e-waste or battery collection point",
    ],
    dos: ["Use approved collection points"],
    donts: ["Do not dispose in household bins"],
    acceptedItems: ["Li-ion packs", "NiMH batteries"],
    rejectedItems: ["Damaged batteries without safe packaging"],
    disposalMethods: ["E-waste center", "Hazardous waste facility"],
    environmentalImpact: "Improper disposal of lithium batteries can cause fires.",
    keywords: ["rechargeable", "battery", "lithium", "nimh", "batt"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Car Battery",
    slug: "car-battery",
    category: "Batteries",
    description: "Lead-acid vehicle batteries must go to specialised scrap or battery recyclers.",
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Keep upright and sealed",
      "Do not drain acid yourself",
      "Take to a scrap collector or hazardous facility",
    ],
    dos: ["Use specialised recyclers"],
    donts: ["Do not put car batteries in household collection"],
    acceptedItems: ["Lead-acid car batteries"],
    rejectedItems: ["Leaking batteries without containment"],
    disposalMethods: ["Scrap collector", "Hazardous waste facility"],
    environmentalImpact: "Lead and acid from car batteries are highly toxic to soil and water.",
    keywords: ["car battery", "vehicle battery", "lead acid", "battery", "batt"],
    faqs: [],
    language: "en",
    status: "published",
  },
  {
    name: "Printer",
    slug: "printer",
    category: "E-Waste",
    description: "Printers and peripherals are e-waste and should go to certified centres.",
    image: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=600&q=80",
    recyclable: true,
    recyclabilityType: "Hazardous",
    preparationInstructions: [
      "Remove ink/toner cartridges if the centre asks",
      "Take to an e-waste centre",
    ],
    dos: ["Use certified e-waste centres"],
    donts: ["Do not dump printers with general waste"],
    acceptedItems: ["Inkjet printers", "Laser printers"],
    rejectedItems: ["Printers in household bins"],
    disposalMethods: ["E-waste center"],
    environmentalImpact: "Printers contain plastics, metals, and sometimes hazardous residues.",
    keywords: ["printer", "electronics", "e-waste", "elec", "toner"],
    faqs: [],
    language: "en",
    status: "published",
  },
];

const CENTERS = [
  {
    name: "Green Colombo Recycling Center",
    description:
      "Demo drop-off centre accepting common household recyclables. Sample data — not an official listing.",
    type: "Recycling Center",
    district: "Colombo",
    municipality: "Colombo Municipal Council",
    address: "Colombo 05",
    location: { type: "Point", coordinates: [79.865, 6.891] },
    phone: "0112345678",
    email: "demo-colombo@example.com",
    website: "",
    openingHours: defaultHours,
    acceptedWaste: ["Plastic", "Paper", "Metal", "Cardboard", "Glass"],
    rejectedWaste: ["Batteries", "Hazardous Household Waste"],
    services: ["Drop-off", "Recycling"],
    verified: true,
    verificationStatus: "Approved",
    isDemo: true,
  },
  {
    name: "Colombo E-Waste Hub (Demo)",
    description: "Demo e-waste collection point. Sample data — not officially certified.",
    type: "E-Waste Center",
    district: "Colombo",
    municipality: "Colombo Municipal Council",
    address: "Colombo 07",
    location: { type: "Point", coordinates: [79.8612, 6.9271] },
    phone: "0118765432",
    email: "demo-ewaste@example.com",
    openingHours: defaultHours,
    acceptedWaste: ["E-Waste", "Batteries"],
    rejectedWaste: ["Organic Waste", "Construction Waste"],
    services: ["Drop-off", "Data wipe inquiry"],
    verified: true,
    verificationStatus: "Approved",
    isDemo: true,
  },
  {
    name: "Kandy Recyclables Point (Demo)",
    description: "Demo recycling drop-off in Kandy. Sample data.",
    type: "Collection Point",
    district: "Kandy",
    municipality: "Kandy Municipal Council",
    address: "Kandy town",
    location: { type: "Point", coordinates: [80.6337, 7.2906] },
    phone: "0812223333",
    openingHours: defaultHours,
    acceptedWaste: ["Plastic", "Paper", "Glass", "Metal"],
    rejectedWaste: ["E-Waste"],
    services: ["Drop-off"],
    verified: true,
    verificationStatus: "Approved",
    isDemo: true,
  },
  {
    name: "Galle Coastal Recycling (Demo)",
    description: "Demo centre near Galle. Sample data — not officially certified.",
    type: "Recycling Center",
    district: "Galle",
    municipality: "Galle Municipal Council",
    address: "Galle Fort area",
    location: { type: "Point", coordinates: [80.217, 6.0535] },
    phone: "0912221111",
    openingHours: defaultHours,
    acceptedWaste: ["Plastic", "Glass", "Metal", "Cardboard"],
    rejectedWaste: ["Hazardous Household Waste"],
    services: ["Drop-off"],
    verified: false,
    verificationStatus: "Pending Verification",
    isDemo: true,
  },
  {
    name: "Negombo Scrap & Metal (Demo)",
    description: "Demo scrap collector listing. Sample data.",
    type: "Scrap Collector",
    district: "Gampaha",
    municipality: "Negombo Municipal Council",
    address: "Negombo",
    location: { type: "Point", coordinates: [79.8358, 7.2083] },
    phone: "0312224444",
    openingHours: defaultHours,
    acceptedWaste: ["Metal", "E-Waste"],
    rejectedWaste: ["Organic Waste"],
    services: ["Pickup inquiry", "Scrap buying"],
    verified: true,
    verificationStatus: "Approved",
    isDemo: true,
  },
  {
    name: "Jaffna Compost Facility (Demo)",
    description: "Demo compost facility. Sample data — not officially certified.",
    type: "Compost Facility",
    district: "Jaffna",
    municipality: "Jaffna Municipal Council",
    address: "Jaffna",
    location: { type: "Point", coordinates: [80.0074, 9.6615] },
    phone: "0212225555",
    openingHours: defaultHours,
    acceptedWaste: ["Organic Waste"],
    rejectedWaste: ["Plastic", "E-Waste", "Batteries"],
    services: ["Drop-off", "Composting"],
    verified: true,
    verificationStatus: "Approved",
    isDemo: true,
  },
  {
    name: "Colombo Textile Donation Point (Demo)",
    description: "Demo donation centre for clothing. Sample data.",
    type: "Donation Center",
    district: "Colombo",
    municipality: "Colombo Municipal Council",
    address: "Colombo 03",
    location: { type: "Point", coordinates: [79.853, 6.9] },
    phone: "0113334444",
    openingHours: {
      ...defaultHours,
      sunday: { open: "09:00", close: "12:00", closed: false },
    },
    acceptedWaste: ["Textiles"],
    rejectedWaste: ["Hazardous Household Waste", "Batteries"],
    services: ["Donation drop-off"],
    verified: false,
    verificationStatus: "Pending Verification",
    isDemo: true,
  },
];

const ARTICLES = [
  {
    title: "How to prepare plastic bottles",
    slug: "how-to-prepare-plastic-bottles",
    summary: "Empty, rinse, and sort PET bottles before drop-off.",
    content:
      "Empty bottles completely, rinse lightly if sticky, and check whether your centre wants caps on or off. Keep soft film separate from rigid PET.",
    category: "Plastic",
    image: "",
    language: "en",
    status: "published",
  },
  {
    title: "How to dispose of batteries safely",
    slug: "how-to-dispose-of-batteries-safely",
    summary: "Never put batteries in household garbage.",
    content:
      "Store used batteries separately and take them to an e-waste or hazardous collection point. Do not crush or burn batteries.",
    category: "Batteries",
    image: "",
    language: "en",
    status: "published",
  },
  {
    title: "What is e-waste?",
    slug: "what-is-e-waste",
    summary: "Electronics that need certified recycling.",
    content:
      "E-waste includes phones, laptops, printers, and similar devices. They contain valuable materials and hazardous components—use certified centres only.",
    category: "E-Waste",
    image: "",
    language: "en",
    status: "published",
  },
  {
    title: "How to start composting at home",
    slug: "how-to-start-composting-at-home",
    summary: "Turn kitchen scraps into soil amendment.",
    content:
      "Use a simple bin with kitchen scraps and dry leaves. Avoid plastics. For meat and dairy, prefer municipal organic collection if available.",
    category: "Organic Waste",
    image: "",
    language: "en",
    status: "published",
  },
  {
    title: "Why burning plastic is harmful",
    slug: "why-burning-plastic-is-harmful",
    summary: "Open burning releases toxic fumes.",
    content:
      "Burning plastic releases harmful chemicals into the air. Recycle clean plastics or dispose through municipal channels instead.",
    category: "Plastic",
    image: "",
    language: "en",
    status: "published",
  },
];

async function seed() {
  await connectDB();
  if (mongoose.connection.readyState !== 1) {
    console.error("Cannot seed: MongoDB is not connected. Check MONGODB_URI / MONGO_URI.");
    process.exit(1);
  }

  console.log("Clearing existing recycling seed collections...");
  await Promise.all([
    WasteGuide.deleteMany({}),
    RecyclingCenter.deleteMany({ isDemo: true }),
    EducationArticle.deleteMany({}),
  ]);

  console.log("Inserting waste guides...");
  await WasteGuide.insertMany(GUIDES);

  console.log("Inserting demo recycling centers...");
  await RecyclingCenter.insertMany(CENTERS);

  console.log("Inserting education articles...");
  await EducationArticle.insertMany(ARTICLES);

  console.log(
    `Seed complete: ${GUIDES.length} guides, ${CENTERS.length} centers, ${ARTICLES.length} articles.`
  );
  console.log("Note: All centers are marked isDemo=true (sample data).");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
